### ISSUE TITLE
Create the client side of the project

### ISSUE THREAD

**Issue by httpiago** [httpiago/graphql-server-with-typescript#5]
Create a visual interface to use graphql server features.

## Tools to be used:
- React (with [CRA](https://github.com/facebook/create-react-app) and [custom server](https://facebook.github.io/create-react-app/docs/deployment#serving-apps-with-client-side-routing)).
- Typescript.
- [Ionic](https://ionicframework.com/docs).
- [Apollo client](https://www.apollographql.com/docs/react/).

## To-dos:
- [ ] Allow singin.
- [ ] Allow auto-login with [credentials api](https://developers.google.com/web/fundamentals/security/credential-management/?hl=pt-br).
- [ ] Allow logout.
- [ ] Allow to create new tweets.
- [ ] Listen for new tweets on the timeline.
- [ ] Allow to like a tweet.
- [ ] Allow to reply to a tweet.
- [ ] Allow to expand a tweet to see the replies.
- [ ] Listen for new replies to a expanded tweet.
- [ ] Allow user to delete their own tweets and replies.

## Details:
- Allow the user to view tweets published without being logged in.
- Reuse the Tweet component to show the answers.
- Only allow the user to interact with the social network if he is logged in.
- Show at the top of the timeline if the app is listening for new tweets.
